#ifndef CQ_OP_CODES_H
#define CQ_OP_CODES_H

enum ctrl_code {
  CQ_CTRL_IDLE = -1,
  CQ_CTRL_INIT,
  CQ_CTRL_ABORT,
  CQ_CTRL_FINALISE,
  CQ_CTRL_ALLOC,
  CQ_CTRL_DEALLOC,
  CQ_CTRL_RUN_QKERNEL,
  CQ_CTRL_RUN_PQKERNEL,
  CQ_CTRL_TEST
};

#endif