cmake_minimum_required(VERSION 4.0)
project(CQSimBERejectedConsumer LANGUAGES C)
if(CHECK_CASE STREQUAL "old-version")
  find_package(CQ-SIMBE 0.1 CONFIG REQUIRED)
elseif(CHECK_CASE STREQUAL "fortran-disabled")
  find_package(CQ-SIMBE 0.2 CONFIG REQUIRED COMPONENTS Fortran)
elseif(CHECK_CASE STREQUAL "fortran-mismatch")
  enable_language(Fortran)
  set(CMAKE_Fortran_COMPILER_VERSION "0.0.0")
  find_package(CQ-SIMBE 0.2 CONFIG REQUIRED COMPONENTS Fortran)
endif()
